In [48]:
import sys
import numpy as np

**Creando un Array**

In [10]:
array1 = np.array([1,2,3]) 

In [12]:
print(array1)

[1 2 3]


In [13]:
array1.ndim  # dimensiones del array

1

In [14]:
array1.shape # estructura del array (filas,columnas)

(3,)

Array en dos dimensiones

In [16]:
array2 = np.array([
                 [1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]
])

In [17]:
print(array2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
array2.ndim # dimensiones del array

2

In [19]:
array2.shape # estructura del array (filas, columnas)

(3, 4)

In [21]:
mat_zeros = np.zeros((3,2)) # crea una matriz de ceros de 3x2

In [22]:
print(mat_zeros)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [23]:
mat_unos = np.ones((6,6))  # crea una matriz de unos de 6x6

In [24]:
mat_unos

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [26]:
mat_iden = np.eye((15)) # crea una matriz identidad de 15x15

In [27]:
mat_iden

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [29]:
mat_rand = np.random.random((5,5)) # crea una matriz de numeros aleatorios de 5x5

In [30]:
mat_rand

array([[0.59050609, 0.19338357, 0.83708835, 0.22967004, 0.79824274],
       [0.92831141, 0.62052052, 0.34829138, 0.83028854, 0.43640677],
       [0.69918644, 0.67189649, 0.90854576, 0.42804104, 0.41056927],
       [0.17930262, 0.24469838, 0.01115084, 0.83948448, 0.82325542],
       [0.87731936, 0.25588554, 0.69511798, 0.61509011, 0.08122982]])

In [31]:
mat_uno = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
])

In [32]:
print(mat_uno)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [33]:
mat_uno[1] # selecciona segundo renglón

array([ 6,  7,  8,  9, 10])

In [35]:
mat_uno[:2]  # selecciona primeros dos renglones

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
mat_uno[:2,:3] # selecciona primeros dos renglones y primeras tres columnas

array([[1, 2, 3],
       [6, 7, 8]])

In [37]:
mat_uno[:,1] # selecciona segunda columna

array([ 2,  7, 12])

In [38]:
mat_uno[0,0] # selecciona elemento de primer renglón y primer columna

1

Matriz diagonal

In [59]:
array_d = np.arange(10,51) # crea valores del 10 al 50

In [60]:
array_d

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [61]:
array_d[0] = 9   # cambiamos el primer valor por 9

In [62]:
array_d

array([ 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [64]:
array_d2 = array_d[1::2]  # seleccionamos los valores impares

In [65]:
array_d2

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43,
       45, 47, 49])

In [68]:
array_d3 = array_d2[:6]   # nos quedamos con los primeros 6 elementos

In [69]:
array_d3

array([11, 13, 15, 17, 19, 21])

In [70]:
array_diag = np.diag(array_d3)  # se crea la matriz diagonal

In [71]:
array_diag

array([[11,  0,  0,  0,  0,  0],
       [ 0, 13,  0,  0,  0,  0],
       [ 0,  0, 15,  0,  0,  0],
       [ 0,  0,  0, 17,  0,  0],
       [ 0,  0,  0,  0, 19,  0],
       [ 0,  0,  0,  0,  0, 21]])

**Suma y Resta de matrices**

In [72]:
array1 = np.array([                   # Se crea primer array de 4x4
         [1,2,3,4],
         [5,6,7,8],
         [9,10,11,12],
         [13,14,15,16]
])

In [73]:
array1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [74]:
array2 = np.array([                   # Se crea primer array de 4x4
         [4,3,2,1],
         [8,7,6,5],
         [12,11,10,9],
         [16,15,14,13]
])

In [75]:
array2

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [76]:
array_sum = array1 + array2   # suma de matrices

In [77]:
array_sum

array([[ 5,  5,  5,  5],
       [13, 13, 13, 13],
       [21, 21, 21, 21],
       [29, 29, 29, 29]])

**Multiplicación de matrices**

In [78]:
array_mul = array1 @ array2    # multiplicación de matrices

In [79]:
array_mul

array([[120, 110, 100,  90],
       [280, 254, 228, 202],
       [440, 398, 356, 314],
       [600, 542, 484, 426]])